{{- if .CreateRbac }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ .AppProxy.AppName }}-cluster-reader
subjects:
- kind: ServiceAccount
  name: {{ .AppProxy.AppName }} # this service account can get secrets cluster-wide (all namespaces)
  namespace: {{ .Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .AppProxy.AppName }}-cluster-reader
  apiGroup: rbac.authorization.k8s.io
{{- end  }}