apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .AppName }}
  namespace: {{ .Namespace }}
  labels:
    app: {{ .AppName }}
    version: {{ .Version }}
spec:
  replicas: {{ default 1 .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 50%
  selector:
    matchLabels:
      app: {{ .AppName }}
  template:
    metadata:
      labels:
        app: {{ .AppName }}
        version: {{ .Version }}
    spec:
      {{- if .Values.rbacEnabled}}
      serviceAccountName: {{ .Release.Name  | quote }}
      {{- end }}
      containers:
      - name: {{ .AppName }}
        image: "{{ .Values.image }}:{{ .Values.imageTag }}"
        imagePullPolicy: Always
        env:
          - name: SERVICE_NAME
            value: {{ .AppName }}
          - name: NAMESPACE_INTERVAL
            value: {{ .Values.namespaceInterval | quote }}
          - name: POD_INTERVAL
            value: {{ .Values.podInterval | quote }}
          - name: DEPLOYMENT_INTERVAL
            value: {{ .Values.deploymentInterval | quote }}
          - name: RELEASE_INTERVAL
            value: {{ .Values.releaseInterval | quote }}
          - name: SERVICE_INTERVAL
            value: {{ .Values.serviceInterval | quote }}
          - name: SECRET_INTERVAL
            value: {{ .Values.secretInterval | quote }}
          {{- if .Values.useNamespaceWideRole }}
          - name: ROLE_BINDING
            value: "true"
          {{- end }}
          - name: PORT
            value: "9020"
          - name: CLUSTER_URL
            value: {{ .Values.clusterUrl | quote }}
          - name: CLUSTER_TOKEN
            value: {{ .Values.clusterToken | quote }}
          - name: CLUSTER_CA
            value: {{ .Values.clusterCA | quote }}
          - name: API_TOKEN
            value: {{ .Values.apiToken | quote }}
          - name: CLUSTER_ID
            value: {{ .Values.clusterId | quote }}
          - name: API_URL
            value: {{ .Values.apiUrl | quote }}
          - name: ACCOUNT_ID
            value: {{ .Values.accountId | quote }}
          - name: DISABLE_HELM
            value: {{ .Values.disableHelm | quote }}
          - name: HELM3
            value: {{ .Values.helm3 | quote }}
          - name: CLEAN
            value: "{{ .Values.clean }}"
          - name: NAMESPACE
            value: "{{ .Namespace }}"
          - name: NODE_OPTIONS
            value: "--max_old_space_size={{ .Values.heapSize }}"
          - name: FORCE_DISABLE_HELM_RELEASES
            value: "{{ .Values.forceDisableHelmReleases }}"
        ports:
        - containerPort: 9020
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /api/ping
            port: 9020
          periodSeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
