apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    {{ if ne .AppProxy.Ingress.IngressClass "" }}kubernetes.io/ingress.class: {{ .AppProxy.Ingress.IngressClass }}{{ end }}
    {{ range $key, $value := .AppProxy.Ingress.Annotations }}
    {{ $key }}: {{ $value | quote | unescape }}
    {{ end }}
  name: app-proxy
  namespace: {{ .Namespace }}
spec:
  rules:
    - host: {{ .AppProxy.Ingress.Host }}
      http:
        paths:
          - path: {{ if .AppProxy.Ingress.PathPrefix }}{{ .AppProxy.Ingress.PathPrefix }}{{ else }}'/'{{end}}
            backend:
              serviceName: app-proxy
              servicePort: 80
  {{ if .AppProxy.Ingress.TLSSecret }}
  tls:
    - hosts:
        - {{ .AppProxy.Ingress.Host }}
      secretName: {{ .AppProxy.Ingress.TLSSecret }}
  {{ end }}
