{{- if .RbacEnabled }}
{{- if .UseNamespaceWideRole }}
kind: Role
{{- else }}
kind: ClusterRole
{{- end }}
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .AppName }}-cluster-reader
  namespace: {{ .Namespace }}
  labels:
    app: {{ .AppName }}
    version: {{ .Version }}
rules:
- apiGroups:
  - ""
  resources: ["*"]
  verbs:
  - get
  - list
  - watch
  - create
  - delete
- apiGroups:
    - ""
  resources: ["pods"]
  verbs:
    - get
    - list
    - watch
    - create
    - deletecollection
- apiGroups:
  - extensions
  resources: ["*"]
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources: ["*"]
  verbs:
  - get
  - list
  - watch
{{- end }}
