# used by:
# - engine pods
{{- if .CreateRbac }}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ .Runtime.EngineAppName }}
  namespace: {{ .Namespace }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
{{- end }}