{{- if .RbacEnabled }}
{{- if .UseNamespaceWideRole }}
kind: RoleBinding
{{- else }}
kind: ClusterRoleBinding
{{- end }}
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .AppName }}-rollback
  namespace: {{ .Namespace }}
  labels:
    app: {{ .AppName }}
    version: {{ .Version }}
subjects:
  - kind: ServiceAccount
    namespace: {{ .Namespace }}
    name: {{ .AppName }}-rollback
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
  {{- end }}
