apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: dind-volume-provisioner-{{ .AppName }}
  namespace: {{ .Namespace }}
  labels:
    app: dind-volume-provisioner
data:
{{- if .Storage.GoogleServiceAccount }}
  google-service-account.json: {{ .Storage.GoogleServiceAccount | b64enc }}
{{- end }}
{{- if .Storage.AwsAccessKeyId }}
  aws_access_key_id: {{ .Storage.AwsAccessKeyId | b64enc }}
{{- end }}
{{- if .Storage.AwsSecretAccessKey }}
  aws_secret_access_key: {{ .Storage.AwsSecretAccessKey | b64enc }}
{{- end }}