apiVersion: v1
kind: Service
metadata:
  name: {{ .AppName }}
  namespace: {{ .Namespace }}
  labels:
    app: {{ .AppName }}
    version: {{ .Version }}
spec:
  type: ClusterIP
  ports:
  - name: "http"
    port: 80
    protocol: TCP
    targetPort: 9020
  selector:
    app: {{ .AppName }}
