apiVersion: v1
kind: Service
metadata:
  name: app-proxy
  namespace: {{ .Namespace }}
spec:
  selector:
    app: {{ .AppProxy.AppName }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
