{{- if .CreateRbac }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Runtime.EngineAppName }}
  namespace: {{ .Namespace }}
  labels:
    app: {{ .AppProxy.AppName }}
    version: {{ .Version }}
{{- end }}
