---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ .Storage.StorageClassName }}
  labels:
    app: dind-volume-provisioner
provisioner: codefresh.io/dind-volume-provisioner-{{ .AppName }}-{{ .Namespace }}
parameters:
{{- if eq .Storage.Backend "local" }}
  volumeBackend: local
  volumeParentDir: {{ .Storage.LocalVolumeParentDir | default "/var/lib/codefresh/dind-volumes" }}
{{- else if eq .Storage.Backend "gcedisk" }}
  volumeBackend: {{ .Storage.Backend }}
  #  pd-ssd or pd-standard
  type: {{ .Storage.VolumeType | default "pd-ssd" }}
  # Valid zone in GCP
  zone: {{ .Storage.AvailabilityZone }}
  # ext4 or xfs (default to ext4 because xfs is not installed on GKE by default )
  fsType: {{ .Storage.FsType | default "ext4" }}
{{- else if or (eq .Storage.Backend "ebs") (eq .Storage.Backend "ebs-csi")}}
  # ebs or ebs-csi
  volumeBackend: {{ .Storage.Backend }}
  #  gp2 or io1
  VolumeType: {{ .Storage.VolumeType | default "gp2" }}
  # Valid zone in aws (us-east-1c, ...)
  AvailabilityZone: {{ .Storage.AvailabilityZone }}
  # ext4 or xfs (default to ext4 )
  fsType: {{ .Storage.FsType | default "ext4" }}
{{- end }}