appProxy:
  enabled: false
  image: "quay.io/codefresh/cf-app-proxy:latest"
  env: { }
  ingress:
    pathPrefix: ""
    class: ""
    host: ""
    tlsSecret: ""
    annotations: { }

newRelicLicense: ""
dockerRegistry: ""

monitor:
  image: "quay.io/codefresh/agent:stable"
  clusterId: ""
  enabled: false
  helm3: false
  token: ""
  env: { }

venona:
  image: "quay.io/codefresh/venona:1.6.7"

volumeProvisioner:
  resources:
  image: "quay.io/codefresh/dind-volume-provisioner:1.31.1"
  mountAzureJson: ""
  createDindVolDirResouces:
    requests:
      cpu:
      memory:
    limits:
      cpu:
      memory:
#todo add envvars

storage:
  backend: local

  local:
    volumeParentDir: /var/lib/codefresh/dind-volumes

  gce:
    volumeType: ""
    availabilityZone: ""
    serviceAccountJson: ""

  ebs:
    volumeType: ""
    availabilityZone: ""
    encrypted: ""
    kmsKeyId: ""
    accessKeyId: ""
    secretAccessKey: ""

  azure:
    resourceGroup: ""
    location: ""
    cachingMode: ""
    skuName: ""

  fsType: "ext4"

  #     resources:
  #       limits:
  #         cpu: 400m
  #         memory: 1200Mi
  #       requests:
  #         cpu: 200m
  #         memory: 500Mi

# todo tolerations
#tolerations: [ ]

global:
  namespace: ""
  codefreshHost: ""
  agentToken: ""
  agentId: ""
  agentName: ""
  accountId: ""
  runtimeName: ""
  keys:
    key: ""
    csr: ""
    ca: ""
    serverCert: ""
