kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ .AppName }}
subjects:
- kind: ServiceAccount
  name: {{ .AppName }}
  namespace: {{ .Env.AGENT_NAMESPACE }}
roleRef:
  kind: ClusterRole
  name: system:discovery
  apiGroup: rbac.authorization.k8s.io